[build]
publish = "output"
# https://github.com/netlify/build-image/issues/221
command = """
cd .. &&
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | /opt/buildhome/python3.7/bin/python -
cd docs &&
poetry run combine build
"""
