[build]
publish = "output"
command = """\
    pip3 install -q poetry && \
    npm install -g yarn && \
    cd .. && \
    poetry install --no-dev && \
    cd docs/theme && \
    ./scripts/install && \
    cd ../ && \
    ls -lah && ls -lah .. && \
    ../.venv/bin/combine build \
    """
