[build]
publish = "output"
# https://github.com/netlify/build-image/issues/221
command = """
pip3 install -q poetry &&
poetry config settings.virtualenvs.in-project true &&
poetry install &&
poetry run combine build
"""
