[build]
publish = "output"
# https://github.com/netlify/build-image/issues/221
command = """
cd .. &&
/opt/buildhome/python3.7/bin/pip install -q poetry &&
poetry install &&
cd docs &&
poetry run combine build
"""
