[build]
publish = "output"
command = """\
    pip3 install -e .. && \
    npm install -g yarn && \
    cd .. && \
    cd docs/theme && \
    ./scripts/install && \
    cd ../ && \
    combine build \
    """
