name: test
on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry
    - run: poetry install
    - run: ./scripts/mypy
    - run: ./scripts/test

  test-min-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install a forked version of pip
      run: pip install git+https://github.com/davegaeddert/pip@prefer-min

    - name: Install package with minimal version selection
      run: python -m pip install . --version-selection=min

    - name: Basic sanity test
      run: combine --help

    - name: Run tests
      run: |
        python -m pip install pytest snapshottest
        pytest tests
